<?php
/**
 * Title: お問い合わせのページ
 * Slug: animewp/contact-page
 * Categories: animewp-example-pages
 * Description: 問い合わせ窓口・よくあるご質問・フォームの置き場所をまとめた固定ページです。メールアドレスと文面を差し替えてください。
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:paragraph {"className":"is-style-animewp-lead"} -->
<p class="is-style-animewp-lead">お問い合わせの前に、よくあるご質問をご確認ください。内容に合った窓口へご連絡いただくと、ご案内がスムーズです。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="faq" style="margin-top:var(--wp--preset--spacing--50)">よくあるご質問</h2>
<!-- /wp:heading -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>放送・配信の日時を知りたい</summary><!-- wp:paragraph -->
<p>最新の放送・配信情報は「放送・配信」ページでお知らせしています。地域や配信サービスによって日時が異なります。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>画像をSNSのアイコンに使ってもよいですか</summary><!-- wp:paragraph -->
<p>作品の画像・映像の転載や加工はご遠慮ください。公式に配布している素材がある場合は、その利用条件に従ってください。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>イベントやグッズについて知りたい</summary><!-- wp:paragraph -->
<p>決まり次第、お知らせでご案内します。販売店・会場ごとのお問い合わせは、各窓口へお願いします。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>サイトの表示がおかしい</summary><!-- wp:paragraph -->
<p>ブラウザーを最新の状態にして、再読み込みをお試しください。改善しない場合は、下記の窓口へお使いの端末とブラウザー名をお知らせください。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="desk" style="margin-top:var(--wp--preset--spacing--50)">お問い合わせ窓口</h2>
<!-- /wp:heading -->

<!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|40"}}}} -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-frame","style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch"}} -->
<div class="wp-block-group is-style-animewp-frame" style="min-height:100%"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">MEDIA</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">取材・掲載のご相談</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>報道・メディア関係の方の、取材や画像掲載のご依頼はこちらへ。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="mailto:press@example.com">メールで問い合わせる</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">press@example.com</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-frame","style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch"}} -->
<div class="wp-block-group is-style-animewp-frame" style="min-height:100%"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">GENERAL</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">作品・サイトについて</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>作品やこのサイトについてのご意見・ご要望はこちらへ。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="mailto:info@example.com">メールで問い合わせる</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">info@example.com</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">※お返事までに数日かかる場合があります。内容によってはお答えできないこともあります。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="form" style="margin-top:var(--wp--preset--spacing--50)">フォームを置く場合</h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"is-style-animewp-soft-panel","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-soft-panel"><!-- wp:paragraph -->
<p><strong>この位置にフォームを追加できます</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>お使いのフォームプラグインのブロックを、この案内と置き換えてください。送信先と、送られた個人情報の扱いを「ご利用について」のページに記載してから公開します。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
