<?php
/**
 * Title: キービジュアル：切り替わる画像とコピー
 * Slug: animewp/example-key-visual
 * Categories: animewp-examples
 * Description: カバー画像をフェードで切り替えるカルーセル。番号で画像を選べます。
 * Requires Blocks: animewp/carousel
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignfull" style="padding-top:0;padding-bottom:0"><!-- wp:animewp/carousel {"effect":"fade","navStyle":"none","dotStyle":"numbers","autoplay":7,"label":"キービジュアル","align":"full","style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-animewp-carousel alignfull has-nav-none is-effect-fade has-dots-numbers" style="--animewp-carousel-slide:100%;--animewp-carousel-gap:0" data-autoplay="7" data-prev-label="前へ" data-next-label="次へ" data-label="キービジュアル" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg","dimRatio":0,"minHeight":86,"minHeightUnit":"vh","contentPosition":"bottom left","isDark":false,"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|50","bottom":"var:preset|spacing|60","left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-cover is-light has-custom-content-position is-position-bottom-left" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--50);min-height:86vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"is-style-animewp-glass","layout":{"type":"constrained","contentSize":"36rem","justifyContent":"left"}} -->
<div class="wp-block-group is-style-animewp-glass"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">TV ANIMATION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"is-style-animewp-display"} -->
<h1 class="wp-block-heading is-style-animewp-display">作品タイトル</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-catchphrase"} -->
<p class="is-style-animewp-catchphrase">物語が、そっと動き出す。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">2026年10月 放送開始</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover -->

<!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg","dimRatio":0,"minHeight":86,"minHeightUnit":"vh","contentPosition":"bottom left","isDark":false,"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|50","bottom":"var:preset|spacing|60","left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-cover is-light has-custom-content-position is-position-bottom-left" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--50);min-height:86vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"is-style-animewp-glass","layout":{"type":"constrained","contentSize":"36rem","justifyContent":"left"}} -->
<div class="wp-block-group is-style-animewp-glass"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">TV ANIMATION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"is-style-animewp-display"} -->
<h1 class="wp-block-heading is-style-animewp-display">作品タイトル</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-catchphrase"} -->
<p class="is-style-animewp-catchphrase">ここから、新しい景色へ。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">2026年10月 放送開始</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div></div>
<!-- /wp:animewp/carousel --></div>
<!-- /wp:group -->
