<?php
/**
 * Title: キャラクター：サムネイルで切り替え
 * Slug: animewp/example-characters
 * Categories: animewp-examples
 * Description: イラストと紹介文。下のサムネイルで人物を切り替えます。
 * Requires Blocks: animewp/carousel
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="characters" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Characters</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">キャラクター</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:animewp/carousel {"effect":"fade","dotStyle":"thumbnails","label":"キャラクター","align":"wide"} -->
<div class="wp-block-animewp-carousel alignwide has-nav-icon is-effect-fade has-dots-thumbnails" style="--animewp-carousel-slide:100%" data-prev-label="前へ" data-next-label="次へ" data-label="キャラクター" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-a.svg" alt="主人公の名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">主人公の名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-b.svg" alt="相棒の名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">相棒の名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-c.svg" alt="ライバルの名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">ライバルの名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:animewp/carousel --></section>
<!-- /wp:group -->
