<?php
/**
 * Title: ストーリー：短い見出しと本文
 * Slug: animewp/example-story
 * Categories: animewp-examples
 * Description: 短い見出し（縦書き・横書きを選べます）、あらすじ、開閉できる各話の紹介。
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained","contentSize":"var(\u002d\u002dwp\u002d\u002dstyle\u002d\u002dglobal\u002d\u002dwide-size)"}} -->
<section class="wp-block-group alignfull" id="story" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Story</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">ストーリー</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"30%"} -->
<div class="wp-block-column" style="flex-basis:30%"><!-- wp:group {"layout":{"type":"flex","justifyContent":"right"}} -->
<div class="wp-block-group"><!-- wp:heading {"level":3,"className":"is-style-animewp-short-vertical"} -->
<h3 class="wp-block-heading is-style-animewp-short-vertical">あの日の約束を、<br>もう一度。</h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>物語のあらすじを入力します。登場人物、舞台、物語が動き出すきっかけを、数段落で紹介します。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>縦書き見出しは短い言葉向けです。狭い画面では自動で横書きに戻ります。</p>
<!-- /wp:paragraph -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>第1話のあらすじ</summary><!-- wp:paragraph -->
<p>各話の紹介を開閉できる形で載せられます。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>第2話のあらすじ</summary><!-- wp:paragraph -->
<p>話数に合わせて複製してください。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->
