<?php
/**
 * Title: 作品紹介：画像と見出し
 * Slug: animewp/example-introduction
 * Categories: animewp-examples
 * Description: 画像とリード文を左右に並べる紹介の区画。
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained","contentSize":"var(\u002d\u002dwp\u002d\u002dstyle\u002d\u002dglobal\u002d\u002dwide-size)"}} -->
<section class="wp-block-group alignfull" id="introduction" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:image {"className":"is-style-animewp-fade-start"} -->
<figure class="wp-block-image is-style-animewp-fade-start"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt="作品の場面写真（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">INTRODUCTION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-animewp-display"} -->
<h2 class="wp-block-heading is-style-animewp-display">作品について</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-lead"} -->
<p class="is-style-animewp-lead">作品の世界と、物語の入口を短く伝えます。ここでは見出し・リード文・本文がそれぞれ独立したブロックです。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>書体や字間は「スタイル → ブロック」の各テキストスタイルでまとめて変えられます。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">ストーリーを読む</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->
