<?php
/**
 * Title: 締めくくり：濃い色の案内
 * Slug: animewp/example-closing
 * Categories: animewp-examples
 * Description: 濃い色の区画で、次の行動（フォロー・放送情報）を案内します。
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","className":"is-style-animewp-contrast","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull is-style-animewp-contrast" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","className":"is-style-animewp-label"} -->
<p class="has-text-align-center is-style-animewp-label">COMING SOON</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","className":"is-style-animewp-display"} -->
<h2 class="wp-block-heading has-text-align-center is-style-animewp-display">物語のつづきは、<br>放送で。</h2>
<!-- /wp:heading -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">公式SNSをフォロー</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">放送情報</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
