<?php
/**
 * Title: 放送・配信：日時の表
 * Slug: animewp/example-on-air
 * Categories: animewp-examples
 * Description: 放送局・配信サービスと日時の表、注意書き、ボタン。
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="onair" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">On Air</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">放送・配信</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><thead><tr><th>放送局・配信</th><th>日時</th></tr></thead><tbody><tr><td>放送局名</td><td>毎週土曜 24:00〜</td></tr><tr><td>配信サービス名</td><td>毎週土曜 24:30〜 順次配信</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">※放送・配信日時は変更になる場合があります。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">配信サービス一覧</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
