<?php
/**
 * Title: 映像：背景が切り替わる動画一覧
 * Slug: animewp/example-movie
 * Categories: animewp-examples
 * Description: 動画カードのカルーセル。背景レイヤーが表示中の映像に合わせて切り替わります。
 * Requires Blocks: animewp/backdrop, animewp/carousel, animewp/video-card
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained","contentSize":"var(\u002d\u002dwp\u002d\u002dstyle\u002d\u002dglobal\u002d\u002dwide-size)"}} -->
<section class="wp-block-group alignfull" id="movie" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:animewp/backdrop {"blur":32,"veil":70} -->
<div class="wp-block-animewp-backdrop is-mode-follow" style="--animewp-backdrop-blur:32px;--animewp-backdrop-veil:0.7;--animewp-backdrop-focus:50% 50%" aria-hidden="true"><span class="animewp-backdrop__veil"></span></div>
<!-- /wp:animewp/backdrop -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Movie</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">映像</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:animewp/carousel {"slideWidth":64,"emphasizeActive":true,"label":"映像","align":"full"} -->
<div class="wp-block-animewp-carousel alignfull has-nav-icon is-effect-slide has-dots-dots is-emphasized" style="--animewp-carousel-slide:64%" data-prev-label="前へ" data-next-label="次へ" data-label="映像" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">TRAILER 01</span><span class="animewp-video-card__title">メイン映像</span></figcaption></figure>
<!-- /wp:animewp/video-card -->

<!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-b.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-b.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">TRAILER 02</span><span class="animewp-video-card__title">ティザー映像</span></figcaption></figure>
<!-- /wp:animewp/video-card -->

<!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">SPECIAL</span><span class="animewp-video-card__title">特別映像</span></figcaption></figure>
<!-- /wp:animewp/video-card --></div></div>
<!-- /wp:animewp/carousel -->

<!-- wp:paragraph {"align":"center","className":"is-style-animewp-caption"} -->
<p class="has-text-align-center is-style-animewp-caption">各カードに動画のURLを設定すると再生ボタンが表示されます。再生すると動画サービスに接続します。</p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->
