<?php
/**
 * Title: ご利用についてのページ
 * Slug: animewp/legal-page
 * Categories: animewp-example-pages
 * Description: 著作権・画像の利用・リンク・推奨環境・個人情報・免責事項をまとめた固定ページです。運営の実情に合わせて内容を確認してください。
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"className":"is-style-animewp-soft-panel","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-soft-panel"><!-- wp:paragraph -->
<p><strong>この文章は見本です</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>運営者や使うサービスに合わせて、公開前に必ず内容を確認・修正してください。法的な判断が必要な場合は専門家にご相談ください。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-animewp-lead","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<p class="is-style-animewp-lead" style="margin-top:var(--wp--preset--spacing--50)">このサイトをご利用いただく前に、以下の内容をご確認ください。ご利用いただいた時点で、これらに同意いただいたものとします。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CONTENTS</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li><a href="#copyright">著作権について</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#images">画像・映像の利用について</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#links">リンクについて</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#environment">推奨環境</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#privacy">個人情報の取り扱い</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#cookies">Cookieとアクセス解析</a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#disclaimer">免責事項</a></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="copyright" style="margin-top:var(--wp--preset--spacing--50)">著作権について</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>このサイトに掲載している文章・画像・映像・音声などの著作権は、作品の権利者または正当な権利を持つ者に帰属します。私的な利用の範囲を超えて、複製・転載・改変・配布することを禁止します。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="images" style="margin-top:var(--wp--preset--spacing--50)">画像・映像の利用について</h2>
<!-- /wp:heading -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>SNSのアイコンやヘッダー、壁紙などへの画像の使用はご遠慮ください。</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>画像・映像の切り抜き、加工、AIの学習データとしての利用を禁止します。</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>公式に配布している素材は、各素材に記載の条件の範囲でご利用ください。</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="links" style="margin-top:var(--wp--preset--spacing--50)">リンクについて</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>このサイトへのリンクは、トップページへのリンクであれば原則として自由です。ただし、作品や権利者の信用を損なうサイトからのリンクはお断りします。画像ファイルへの直接のリンクはご遠慮ください。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="environment" style="margin-top:var(--wp--preset--spacing--50)">推奨環境</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>次のブラウザーの最新版でご覧ください。JavaScript を有効にしてください。</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>パソコン：Chrome、Edge、Firefox、Safari</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>スマートフォン：iOS の Safari、Android の Chrome</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="privacy" style="margin-top:var(--wp--preset--spacing--50)">個人情報の取り扱い</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>お問い合わせなどで受け取った氏名・メールアドレスなどの個人情報は、ご連絡への対応のためにのみ使用し、法令に基づく場合を除いて第三者に提供しません。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="cookies" style="margin-top:var(--wp--preset--spacing--50)">Cookieとアクセス解析</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>このサイトでは、利用状況を把握するためにアクセス解析ツールを使うことがあります。データは Cookie を使って匿名で収集され、個人を特定するものではありません。Cookie はブラウザーの設定で無効にできます。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">※動画を再生すると、動画サービスに接続し、そのサービスの Cookie が使われる場合があります。</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"fontSize":"large","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<h2 class="wp-block-heading has-large-font-size" id="disclaimer" style="margin-top:var(--wp--preset--spacing--50)">免責事項</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>掲載内容には十分に注意していますが、正確性や安全性を保証するものではありません。このサイトの利用によって生じた損害について、責任を負いかねます。掲載内容は予告なく変更・削除することがあります。</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"className":"is-style-wide","style":{"spacing":{"margin":{"top":"var:preset|spacing|50"}}}} -->
<hr class="wp-block-separator has-alpha-channel-opacity is-style-wide" style="margin-top:var(--wp--preset--spacing--50)"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">© 原作者名／出版社名・作品名製作委員会</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">制定日：2026年10月1日</p>
<!-- /wp:paragraph -->
