<?php
/**
 * Title: 見本ページ：花びらが舞う
 * Slug: animewp/page-drift
 * Categories: animewp-example-pages
 * Description: 同じ区画に、ゆっくり浮かぶ花びらとパララックスを加えた見本です。
 * Requires Blocks: animewp/backdrop, animewp/carousel, animewp/decoration, animewp/video-card
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group alignfull" style="padding-top:0;padding-bottom:0"><!-- wp:animewp/decoration {"shape":"petal","x":8,"y":18,"size":3,"rotation":-25,"opacity":70,"layer":"front","textColor":"accent","animewpMotion":{"loop":"float","parallax":-15}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-front has-accent-color has-text-color" style="--animewp-decoration-x:8%;--animewp-decoration-y:18%;--animewp-decoration-size:3%;--animewp-decoration-rotation:-25deg;--animewp-decoration-opacity:0.7" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"shape":"petal","x":92,"y":70,"size":5,"rotation":35,"opacity":45,"layer":"front","textColor":"accent","animewpMotion":{"loop":"sway","parallax":20}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-front has-accent-color has-text-color" style="--animewp-decoration-x:92%;--animewp-decoration-y:70%;--animewp-decoration-size:5%;--animewp-decoration-rotation:35deg;--animewp-decoration-opacity:0.45" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"x":75,"y":12,"size":2,"opacity":60,"layer":"front","textColor":"muted","animewpMotion":{"loop":"pulse"}} -->
<div class="wp-block-animewp-decoration is-shape-sparkle is-layer-front has-muted-color has-text-color" style="--animewp-decoration-x:75%;--animewp-decoration-y:12%;--animewp-decoration-size:2%;--animewp-decoration-rotation:0deg;--animewp-decoration-opacity:0.6" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/carousel {"effect":"fade","navStyle":"none","dotStyle":"numbers","autoplay":7,"label":"キービジュアル","align":"full","style":{"spacing":{"blockGap":"0"}}} -->
<div class="wp-block-animewp-carousel alignfull has-nav-none is-effect-fade has-dots-numbers" style="--animewp-carousel-slide:100%;--animewp-carousel-gap:0" data-autoplay="7" data-prev-label="前へ" data-next-label="次へ" data-label="キービジュアル" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg","dimRatio":0,"minHeight":86,"minHeightUnit":"vh","contentPosition":"bottom left","isDark":false,"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|50","bottom":"var:preset|spacing|60","left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-cover is-light has-custom-content-position is-position-bottom-left" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--50);min-height:86vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"is-style-animewp-glass","layout":{"type":"constrained","contentSize":"36rem","justifyContent":"left"}} -->
<div class="wp-block-group is-style-animewp-glass"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">TV ANIMATION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"is-style-animewp-display"} -->
<h1 class="wp-block-heading is-style-animewp-display">作品タイトル</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-catchphrase"} -->
<p class="is-style-animewp-catchphrase">物語が、そっと動き出す。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">2026年10月 放送開始</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover -->

<!-- wp:cover {"url":"<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg","dimRatio":0,"minHeight":86,"minHeightUnit":"vh","contentPosition":"bottom left","isDark":false,"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|50","bottom":"var:preset|spacing|60","left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-cover is-light has-custom-content-position is-position-bottom-left" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--50);min-height:86vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="" src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"className":"is-style-animewp-glass","layout":{"type":"constrained","contentSize":"36rem","justifyContent":"left"}} -->
<div class="wp-block-group is-style-animewp-glass"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">TV ANIMATION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"is-style-animewp-display"} -->
<h1 class="wp-block-heading is-style-animewp-display">作品タイトル</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-catchphrase"} -->
<p class="is-style-animewp-catchphrase">ここから、新しい景色へ。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">2026年10月 放送開始</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div></div>
<!-- /wp:animewp/carousel --></div>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="introduction" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:image {"className":"is-style-animewp-fade-start"} -->
<figure class="wp-block-image is-style-animewp-fade-start"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt="作品の場面写真（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">INTRODUCTION</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-animewp-display"} -->
<h2 class="wp-block-heading is-style-animewp-display">作品について</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-lead"} -->
<p class="is-style-animewp-lead">作品の世界と、物語の入口を短く伝えます。ここでは見出し・リード文・本文がそれぞれ独立したブロックです。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>書体や字間は「スタイル → ブロック」の各テキストスタイルでまとめて変えられます。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">ストーリーを読む</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="story" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Story</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">ストーリー</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":"30%"} -->
<div class="wp-block-column" style="flex-basis:30%"><!-- wp:heading {"level":3,"className":"is-style-animewp-short-vertical"} -->
<h3 class="wp-block-heading is-style-animewp-short-vertical">あの日の約束を、<br>もう一度。</h3>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>物語のあらすじを入力します。登場人物、舞台、物語が動き出すきっかけを、数段落で紹介します。</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>縦書き見出しは短い言葉向けです。狭い画面では自動で横書きに戻ります。</p>
<!-- /wp:paragraph -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>第1話のあらすじ</summary><!-- wp:paragraph -->
<p>各話の紹介を開閉できる形で載せられます。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details -->

<!-- wp:details {"className":"is-style-animewp-details"} -->
<details class="wp-block-details is-style-animewp-details"><summary>第2話のあらすじ</summary><!-- wp:paragraph -->
<p>話数に合わせて複製してください。</p>
<!-- /wp:paragraph --></details>
<!-- /wp:details --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="movie" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:animewp/backdrop {"blur":32,"veil":70} -->
<div class="wp-block-animewp-backdrop is-mode-follow" style="--animewp-backdrop-blur:32px;--animewp-backdrop-veil:0.7;--animewp-backdrop-focus:50% 50%" aria-hidden="true"><span class="animewp-backdrop__veil"></span></div>
<!-- /wp:animewp/backdrop -->

<!-- wp:animewp/decoration {"shape":"petal","x":8,"y":18,"size":3,"rotation":-25,"opacity":70,"textColor":"accent","animewpMotion":{"loop":"float","parallax":-15}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-behind has-accent-color has-text-color" style="--animewp-decoration-x:8%;--animewp-decoration-y:18%;--animewp-decoration-size:3%;--animewp-decoration-rotation:-25deg;--animewp-decoration-opacity:0.7" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"shape":"petal","x":92,"y":70,"size":5,"rotation":35,"opacity":45,"textColor":"accent","animewpMotion":{"loop":"sway","parallax":20}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-behind has-accent-color has-text-color" style="--animewp-decoration-x:92%;--animewp-decoration-y:70%;--animewp-decoration-size:5%;--animewp-decoration-rotation:35deg;--animewp-decoration-opacity:0.45" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"x":75,"y":12,"size":2,"opacity":60,"textColor":"muted","animewpMotion":{"loop":"pulse"}} -->
<div class="wp-block-animewp-decoration is-shape-sparkle is-layer-behind has-muted-color has-text-color" style="--animewp-decoration-x:75%;--animewp-decoration-y:12%;--animewp-decoration-size:2%;--animewp-decoration-rotation:0deg;--animewp-decoration-opacity:0.6" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Movie</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">映像</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:animewp/carousel {"slideWidth":64,"emphasizeActive":true,"label":"映像","align":"full","animewpMotion":{"entrance":"fade"}} -->
<div class="wp-block-animewp-carousel alignfull has-nav-icon is-effect-slide has-dots-dots is-emphasized" style="--animewp-carousel-slide:64%" data-prev-label="前へ" data-next-label="次へ" data-label="映像" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">TRAILER 01</span><span class="animewp-video-card__title">メイン映像</span></figcaption></figure>
<!-- /wp:animewp/video-card -->

<!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-b.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-b.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">TRAILER 02</span><span class="animewp-video-card__title">ティザー映像</span></figcaption></figure>
<!-- /wp:animewp/video-card -->

<!-- wp:animewp/video-card {"posterUrl":"<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg"} -->
<figure style="--animewp-video-card-ratio:16/9" class="wp-block-animewp-video-card"><span class="animewp-video-card__frame"><img src="<?php echo esc_url( wp_make_link_relative( get_theme_file_uri( 'assets/images/' ) ) ); ?>animewp-key-visual-a.svg" alt="" loading="lazy" decoding="async"/></span><figcaption class="animewp-video-card__caption"><span class="animewp-video-card__label">SPECIAL</span><span class="animewp-video-card__title">特別映像</span></figcaption></figure>
<!-- /wp:animewp/video-card --></div></div>
<!-- /wp:animewp/carousel -->

<!-- wp:paragraph {"align":"center","className":"is-style-animewp-caption"} -->
<p class="has-text-align-center is-style-animewp-caption">各カードに動画のURLを設定すると再生ボタンが表示されます。再生すると動画サービスに接続します。</p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="characters" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Characters</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">キャラクター</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:animewp/carousel {"effect":"fade","dotStyle":"thumbnails","label":"キャラクター","align":"wide"} -->
<div class="wp-block-animewp-carousel alignwide has-nav-icon is-effect-fade has-dots-thumbnails" style="--animewp-carousel-slide:100%" data-prev-label="前へ" data-next-label="次へ" data-label="キャラクター" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-a.svg" alt="主人公の名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">主人公の名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-b.svg" alt="相棒の名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">相棒の名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"verticalAlignment":"center","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|50"}}}} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"width":"42%"} -->
<div class="wp-block-column" style="flex-basis:42%"><!-- wp:image {"className":"is-style-animewp-portrait"} -->
<figure class="wp-block-image is-style-animewp-portrait"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-c.svg" alt="ライバルの名前のイラスト（差し替えてください）"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CHARACTER 03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">ライバルの名前</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">CV：声優名</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>人物の紹介文を入力します。性格や物語での役割を短く伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:animewp/carousel --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="staff" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Staff &amp; Cast</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">スタッフ・キャスト</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">STAFF</p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><tbody><tr><td>原作</td><td>名前</td></tr><tr><td>監督</td><td>名前</td></tr><tr><td>シリーズ構成</td><td>名前</td></tr><tr><td>キャラクターデザイン</td><td>名前</td></tr><tr><td>音楽</td><td>名前</td></tr><tr><td>アニメーション制作</td><td>スタジオ名</td></tr></tbody></table></figure>
<!-- /wp:table --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">CAST</p>
<!-- /wp:paragraph -->

<!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><tbody><tr><td>主人公の名前</td><td>声優名</td></tr><tr><td>相棒の名前</td><td>声優名</td></tr><tr><td>ライバルの名前</td><td>声優名</td></tr></tbody></table></figure>
<!-- /wp:table --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="onair" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">On Air</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">放送・配信</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:table -->
<figure class="wp-block-table"><table class="has-fixed-layout"><thead><tr><th>放送局・配信</th><th>日時</th></tr></thead><tbody><tr><td>放送局名</td><td>毎週土曜 24:00〜</td></tr><tr><td>配信サービス名</td><td>毎週土曜 24:30〜 順次配信</td></tr></tbody></table></figure>
<!-- /wp:table -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">※放送・配信日時は変更になる場合があります。</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">配信サービス一覧</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull" id="news" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">News</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">お知らせ</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:pattern {"slug":"animewp/news-index"} /-->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"right"}} -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">お知らせ一覧</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","align":"full","className":"is-style-animewp-contrast","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} -->
<section class="wp-block-group alignfull is-style-animewp-contrast" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:animewp/decoration {"shape":"petal","x":8,"y":18,"size":3,"rotation":-25,"opacity":70,"textColor":"accent","animewpMotion":{"loop":"float","parallax":-15}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-behind has-accent-color has-text-color" style="--animewp-decoration-x:8%;--animewp-decoration-y:18%;--animewp-decoration-size:3%;--animewp-decoration-rotation:-25deg;--animewp-decoration-opacity:0.7" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"shape":"petal","x":92,"y":70,"size":5,"rotation":35,"opacity":45,"textColor":"accent","animewpMotion":{"loop":"sway","parallax":20}} -->
<div class="wp-block-animewp-decoration is-shape-petal is-layer-behind has-accent-color has-text-color" style="--animewp-decoration-x:92%;--animewp-decoration-y:70%;--animewp-decoration-size:5%;--animewp-decoration-rotation:35deg;--animewp-decoration-opacity:0.45" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:animewp/decoration {"x":75,"y":12,"size":2,"opacity":60,"textColor":"muted","animewpMotion":{"loop":"pulse"}} -->
<div class="wp-block-animewp-decoration is-shape-sparkle is-layer-behind has-muted-color has-text-color" style="--animewp-decoration-x:75%;--animewp-decoration-y:12%;--animewp-decoration-size:2%;--animewp-decoration-rotation:0deg;--animewp-decoration-opacity:0.6" aria-hidden="true"><span class="animewp-decoration__art"></span></div>
<!-- /wp:animewp/decoration -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"center","className":"is-style-animewp-label"} -->
<p class="has-text-align-center is-style-animewp-label">COMING SOON</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"textAlign":"center","className":"is-style-animewp-display"} -->
<h2 class="wp-block-heading has-text-align-center is-style-animewp-display">物語のつづきは、<br>放送で。</h2>
<!-- /wp:heading -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">公式SNSをフォロー</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">放送情報</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
