<?php
/**
 * Title: スタイル見本：すべての部品と動き
 * Slug: animewp/style-guide
 * Categories: animewp-example-pages
 * Description: テキストスタイル、区画のスタイル、ボタン、カルーセルの操作、モーションを一覧できます。デザインを変えた後の確認にも使えます。
 * Requires Blocks: animewp/carousel
 * Viewport Width: 1280
 *
 * Generated by scripts/build-examples.js from scripts/examples. Edit the source and rebuild.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<!-- wp:group {"align":"wide","layout":{"type":"constrained","contentSize":"1180px"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"style":{"spacing":{"blockGap":"0.25rem","margin":{"bottom":"var:preset|spacing|40"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-latin"} -->
<h2 class="wp-block-heading is-style-animewp-latin">Style Guide</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">スタイル見本</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Text styles / テキストスタイル</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">スタイル → ブロック → 段落／見出し で一括変更</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-kicker</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-kicker"} -->
<p class="is-style-animewp-kicker">補助見出し</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-label</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-label"} -->
<p class="is-style-animewp-label">ENGLISH LABEL</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-lead</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-lead"} -->
<p class="is-style-animewp-lead">リード文：段落の最初で、内容の要点を少し大きく伝えます。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-catchphrase</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-catchphrase"} -->
<p class="is-style-animewp-catchphrase">キャッチコピー：物語が、そっと動き出す。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-caption</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">キャプション：画像や表の補足に使います。</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-highlight</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-animewp-highlight"} -->
<p class="is-style-animewp-highlight">文字の背景ハイライト</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-display</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-display"} -->
<h3 class="wp-block-heading is-style-animewp-display">大見出し（明朝・広い字間）</h3>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-animewp-caption","style":{"layout":{"selfStretch":"fixed","flexSize":"12rem"}}} -->
<p class="is-style-animewp-caption">animewp-latin</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"is-style-animewp-latin"} -->
<h3 class="wp-block-heading is-style-animewp-latin">Latin Heading</h3>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Section styles / 区画のスタイル</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">スタイル → ブロック → グループ で一括変更</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-surface","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-surface"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">淡い色面</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-surface</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">カード</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-card</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-frame","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-frame"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">細いフレーム</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-frame</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-soft-panel","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-soft-panel"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">淡い背景</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-soft-panel</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-accent","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-accent"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">強調色の面</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-accent</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-contrast","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-contrast"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">濃い面</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-contrast</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-glass","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-glass"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">すりガラス</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>is-style-animewp-glass</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Buttons / ボタン</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">スタイル → ブロック → ボタン、またはスタイル → 要素 → ボタン</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">塗り</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="#">線</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Carousel / カルーセル</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">各カルーセルの「操作」設定で切り替え</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">navStyle: icon / dotStyle: dots</p>
<!-- /wp:paragraph -->

<!-- wp:animewp/carousel {"label":"見本画像"} -->
<div class="wp-block-animewp-carousel has-nav-icon is-effect-slide has-dots-dots" style="--animewp-carousel-slide:100%" data-prev-label="前へ" data-next-label="次へ" data-label="見本画像" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg" alt="見本画像1"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt="見本画像2"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-d.svg" alt="見本画像3"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:animewp/carousel --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">navStyle: text / dotStyle: numbers</p>
<!-- /wp:paragraph -->

<!-- wp:animewp/carousel {"navStyle":"text","dotStyle":"numbers","prevLabel":"PREV","nextLabel":"NEXT","label":"見本画像"} -->
<div class="wp-block-animewp-carousel has-nav-text is-effect-slide has-dots-numbers" style="--animewp-carousel-slide:100%" data-prev-label="PREV" data-next-label="NEXT" data-label="見本画像" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg" alt="見本画像1"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt="見本画像2"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-d.svg" alt="見本画像3"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:animewp/carousel --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">navStyle: line / dotStyle: thumbnails</p>
<!-- /wp:paragraph -->

<!-- wp:animewp/carousel {"effect":"fade","navStyle":"line","dotStyle":"thumbnails","prevLabel":"PREV","nextLabel":"NEXT","label":"見本画像"} -->
<div class="wp-block-animewp-carousel has-nav-line is-effect-fade has-dots-thumbnails" style="--animewp-carousel-slide:100%" data-prev-label="PREV" data-next-label="NEXT" data-label="見本画像" data-pause-label="自動切り替えを一時停止"><div class="animewp-carousel__track"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-a.svg" alt="見本画像1"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt="見本画像2"/></figure>
<!-- /wp:image -->

<!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-character-d.svg" alt="見本画像3"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:animewp/carousel --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Entrances / 登場の動き</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">各ブロックの「モーション → 登場」</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">フェードイン</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: fade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">下から浮かぶ</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: rise</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">行頭側からスライド</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: slide-start</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">行末側からスライド</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: slide-end</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">ズームイン</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: zoom</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">ぼかしから鮮明に</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: blur</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">ワイプ</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: mask</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">1文字ずつ</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">entrance: letters</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40"}},"border":{"top":{"color":"var:preset|color|border","width":"1px"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;padding-top:var(--wp--preset--spacing--40);padding-bottom:var(--wp--preset--spacing--40)"><!-- wp:heading {"className":"is-style-animewp-label"} -->
<h2 class="wp-block-heading is-style-animewp-label">Hover / ポインターを合わせたとき</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">各ブロックの「モーション → ポインターを合わせたとき」</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">浮き上がる</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">hover: lift</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">画像を拡大</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">hover: zoom</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"className":"is-style-animewp-card","layout":{"type":"default"}} -->
<div class="wp-block-group is-style-animewp-card"><!-- wp:image -->
<figure class="wp-block-image"><img src="<?php echo esc_url( get_theme_file_uri( 'assets/images/' ) ); ?>animewp-key-visual-b.svg" alt=""/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">光る</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-animewp-caption"} -->
<p class="is-style-animewp-caption">hover: glow</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
