#!/usr/bin/env python3
"""Generate the editable palette and the legacy compatibility stylesheet.

inc/design-tokens.json is the source:
- palette: the color roles shown in Styles → Colors (written into theme.json).
- legacyAliases / legacyColors / legacyFontRoles: presets from 1.x that saved
  posts may still reference. They stay out of the pickers; compat.css keeps
  their classes and CSS variables working at the lowest specificity, so a
  value saved in Global Styles still wins.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / "themes/animewp"


def encoded(data):
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def compat_css(config):
    variables = []
    rules = []
    for legacy, role in config["legacyAliases"].items():
        variables.append(f"--wp--preset--color--{role}: var(--wp--preset--color--{legacy});")
    for slug, value in config["legacyColors"].items():
        variables.append(f"--wp--preset--color--{slug}: {value};")
    for slug in list(config["legacyAliases"].values()) + list(config["legacyColors"]):
        variable = f"var(--wp--preset--color--{slug})"
        rules += [
            f":where(.has-{slug}-color) {{ color: {variable} !important; }}",
            f":where(.has-{slug}-background-color) {{ background-color: {variable} !important; }}",
            f":where(.has-{slug}-border-color) {{ border-color: {variable} !important; }}",
        ]
    for role, stack in config["legacyFontRoles"].items():
        variables.append(f"--wp--preset--font-family--animewp-role-{role}: var(--animewp-role-{role}, {stack});")
        rules.append(f":where(.has-animewp-role-{role}-font-family) {{ font-family: var(--wp--preset--font-family--animewp-role-{role}) !important; }}")
    header = "/* Generated by scripts/design_tokens.py from inc/design-tokens.json. Do not edit.\n * 1.x presets that saved content may reference; hidden from pickers, kept working. */\n"
    return header + ":where(:root) {\n" + "".join(f"  {line}\n" for line in variables) + "}\n" + "".join(f"{rule}\n" for rule in rules)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    config = json.loads((THEME / "inc/design-tokens.json").read_text())
    theme = json.loads((THEME / "theme.json").read_text())
    theme["settings"]["color"]["palette"] = config["palette"]
    outputs = {THEME / "theme.json": encoded(theme), THEME / "assets/css/compat.css": compat_css(config)}
    for path, value in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != value:
                raise SystemExit(f"Design tokens out of date: {path.relative_to(ROOT)} (run scripts/design_tokens.py)")
        else:
            path.write_text(value)
    print(f"Design tokens {'verified' if args.check else 'generated'}: {len(config['palette'])} color roles, legacy presets in compat.css.")


if __name__ == "__main__":
    main()
