<?php
/**
 * Theme setup and presentation.
 *
 * @package animewp
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

require_once __DIR__ . '/inc/distribution-updater.php';

function animewp_setup() {
	load_theme_textdomain( 'animewp', get_template_directory() . '/languages' );
	// Block template canvas renders the document title.
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'custom-logo', array( 'height' => 80, 'width' => 240, 'flex-height' => true, 'flex-width' => true ) );
	add_editor_style( array( 'assets/css/compat.css', 'assets/css/animewp.css', 'assets/css/editor.css' ) );
}
add_action( 'after_setup_theme', 'animewp_setup' );

function animewp_assets() {
	wp_enqueue_style( 'animewp-compat', get_theme_file_uri( 'assets/css/compat.css' ), array(), wp_get_theme()->get( 'Version' ) );
	wp_enqueue_style( 'animewp-theme', get_theme_file_uri( 'assets/css/animewp.css' ), array( 'animewp-compat' ), wp_get_theme()->get( 'Version' ) );
	// Front end only: spacing defaults for content saved before 2.0 (see the file header).
	wp_enqueue_style( 'animewp-defaults', get_theme_file_uri( 'assets/css/defaults.css' ), array( 'animewp-theme' ), wp_get_theme()->get( 'Version' ) );
	wp_enqueue_script( 'animewp-presentation', get_theme_file_uri( 'assets/js/presentation.js' ), array(), wp_get_theme()->get( 'Version' ), array( 'in_footer' => true, 'strategy' => 'defer' ) );
	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'animewp_assets' );

function animewp_body_classes( $classes ) {
	$classes[] = 'animewp-theme';
	return $classes;
}
add_filter( 'body_class', 'animewp_body_classes' );

function animewp_register_designs() {
	register_block_pattern_category( 'animewp-examples', array( 'label' => __( 'animewp：区画の見本', 'animewp' ) ) );
	register_block_pattern_category( 'animewp-example-pages', array( 'label' => __( 'animewp：ページの見本', 'animewp' ) ) );
	register_block_pattern_category( 'animewp-headers', array( 'label' => __( 'animewp：ヘッダー', 'animewp' ) ) );
	register_block_pattern_category( 'animewp-footers', array( 'label' => __( 'animewp：フッター', 'animewp' ) ) );
	// Text and section styles with editable typography/colors live in styles/*.json
	// (Styles → Blocks → …). These remaining styles are decorative behaviour only.
	$styles = array(
		'core/group'     => array( 'animewp-reveal' => __( 'animewp：控えめに表示', 'animewp' ), 'animewp-texture' => __( 'animewp：細い罫線のテクスチャ', 'animewp' ) ),
		'core/details'   => array( 'animewp-details' => __( 'animewp：開閉カード', 'animewp' ) ),
		'core/image'     => array( 'animewp-portrait' => __( 'animewp：人物画像', 'animewp' ), 'animewp-fade-start' => __( 'animewp：左端をフェード', 'animewp' ), 'animewp-fade-bottom' => __( 'animewp：下端をフェード', 'animewp' ) ),
	);
	foreach ( $styles as $block_name => $definitions ) {
		foreach ( $definitions as $name => $label ) {
			register_block_style( $block_name, array( 'name' => $name, 'label' => $label ) );
		}
	}
}
add_action( 'init', 'animewp_register_designs' );

require_once get_theme_file_path( 'inc/starters.php' );
require_once get_theme_file_path( 'inc/design-settings.php' );

/**
 * Examples in examples/*.php are generated by scripts/build-examples.js. An
 * example that uses AnimeWP Blocks is registered only when those blocks are.
 */
function animewp_register_examples() {
	$registry = WP_Block_Type_Registry::get_instance();
	$headers  = array( 'title' => 'Title', 'slug' => 'Slug', 'categories' => 'Categories', 'description' => 'Description', 'requires' => 'Requires Blocks', 'viewport' => 'Viewport Width' );
	foreach ( glob( get_theme_file_path( 'examples/*.php' ) ) as $file ) {
		$data     = get_file_data( $file, $headers );
		$requires = array_filter( array_map( 'trim', explode( ',', $data['requires'] ) ) );
		foreach ( $requires as $name ) {
			if ( ! $registry->is_registered( $name ) ) {
				continue 2;
			}
		}
		ob_start();
		include $file;
		register_block_pattern(
			$data['slug'],
			array(
				'title'         => $data['title'],
				'description'   => $data['description'],
				'categories'    => array_filter( array_map( 'trim', explode( ',', $data['categories'] ) ) ),
				'content'       => ob_get_clean(),
				'viewportWidth' => (int) $data['viewport'] ? (int) $data['viewport'] : 1280,
			)
		);
	}
}
// After plugins register their blocks on init.
add_action( 'init', 'animewp_register_examples', 20 );
